### ISSUE TITLE
Går att flytta denna logik till basklassen

### ISSUE THREAD

**Issue by ntijoh-daniel-berg** [Itggot-Victor-Ek/webbserverprojekt#10]
Ex (i basklassen)

column('username', required: true, **unique: true**)

https://github.com/Itggot-Victor-Ek/webbserverprojekt/blob/e14ece600630757eda4144c8533593d8cdfbd777/models/users.rb#L64-L132

**Comment by Victor-Ek** [comment]
efter att ha frågat dig igår tror jag att jag nu gjort detta i mina commits ca044e5 , 1d5db56  samt 16ec5c7
